# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import collector_pb2 as collector__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in collector_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CollectorPeerStub(object):
    """CollectorPeer — gRPC service between poll-workers/forwarder and their local cache-node.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMyJobs = channel.unary_unary(
                '/collector.CollectorPeer/GetMyJobs',
                request_serializer=collector__pb2.GetJobsRequest.SerializeToString,
                response_deserializer=collector__pb2.GetJobsResponse.FromString,
                _registered_method=True)
        self.ReportExecution = channel.unary_unary(
                '/collector.CollectorPeer/ReportExecution',
                request_serializer=collector__pb2.ReportExecutionReq.SerializeToString,
                response_deserializer=collector__pb2.ReportExecutionResp.FromString,
                _registered_method=True)
        self.RegisterWorker = channel.unary_unary(
                '/collector.CollectorPeer/RegisterWorker',
                request_serializer=collector__pb2.RegisterWorkerReq.SerializeToString,
                response_deserializer=collector__pb2.RegisterWorkerResp.FromString,
                _registered_method=True)
        self.GetCredential = channel.unary_unary(
                '/collector.CollectorPeer/GetCredential',
                request_serializer=collector__pb2.CredentialRequest.SerializeToString,
                response_deserializer=collector__pb2.CredentialResponse.FromString,
                _registered_method=True)
        self.SubmitResult = channel.unary_unary(
                '/collector.CollectorPeer/SubmitResult',
                request_serializer=collector__pb2.SubmitResultRequest.SerializeToString,
                response_deserializer=collector__pb2.SubmitResultResponse.FromString,
                _registered_method=True)
        self.GetAppCode = channel.unary_unary(
                '/collector.CollectorPeer/GetAppCode',
                request_serializer=collector__pb2.AppCodeRequest.SerializeToString,
                response_deserializer=collector__pb2.AppCodeResponse.FromString,
                _registered_method=True)
        self.AppCacheGet = channel.unary_unary(
                '/collector.CollectorPeer/AppCacheGet',
                request_serializer=collector__pb2.AppCacheGetRequest.SerializeToString,
                response_deserializer=collector__pb2.AppCacheGetResponse.FromString,
                _registered_method=True)
        self.AppCacheSet = channel.unary_unary(
                '/collector.CollectorPeer/AppCacheSet',
                request_serializer=collector__pb2.AppCacheSetRequest.SerializeToString,
                response_deserializer=collector__pb2.AppCacheSetResponse.FromString,
                _registered_method=True)
        self.AppCacheDelete = channel.unary_unary(
                '/collector.CollectorPeer/AppCacheDelete',
                request_serializer=collector__pb2.AppCacheDeleteRequest.SerializeToString,
                response_deserializer=collector__pb2.AppCacheDeleteResponse.FromString,
                _registered_method=True)


class CollectorPeerServicer(object):
    """CollectorPeer — gRPC service between poll-workers/forwarder and their local cache-node.
    """

    def GetMyJobs(self, request, context):
        """Job distribution (poll-worker → local cache-node)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportExecution(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterWorker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCredential(self, request, context):
        """Credential fetch (poll-worker → local cache-node)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitResult(self, request, context):
        """Result submission (poll-worker/forwarder → local cache-node)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAppCode(self, request, context):
        """App code distribution (poll-worker → local cache-node)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AppCacheGet(self, request, context):
        """App cache (poll-worker → local cache-node)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AppCacheSet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AppCacheDelete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CollectorPeerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMyJobs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMyJobs,
                    request_deserializer=collector__pb2.GetJobsRequest.FromString,
                    response_serializer=collector__pb2.GetJobsResponse.SerializeToString,
            ),
            'ReportExecution': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportExecution,
                    request_deserializer=collector__pb2.ReportExecutionReq.FromString,
                    response_serializer=collector__pb2.ReportExecutionResp.SerializeToString,
            ),
            'RegisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorker,
                    request_deserializer=collector__pb2.RegisterWorkerReq.FromString,
                    response_serializer=collector__pb2.RegisterWorkerResp.SerializeToString,
            ),
            'GetCredential': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCredential,
                    request_deserializer=collector__pb2.CredentialRequest.FromString,
                    response_serializer=collector__pb2.CredentialResponse.SerializeToString,
            ),
            'SubmitResult': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitResult,
                    request_deserializer=collector__pb2.SubmitResultRequest.FromString,
                    response_serializer=collector__pb2.SubmitResultResponse.SerializeToString,
            ),
            'GetAppCode': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAppCode,
                    request_deserializer=collector__pb2.AppCodeRequest.FromString,
                    response_serializer=collector__pb2.AppCodeResponse.SerializeToString,
            ),
            'AppCacheGet': grpc.unary_unary_rpc_method_handler(
                    servicer.AppCacheGet,
                    request_deserializer=collector__pb2.AppCacheGetRequest.FromString,
                    response_serializer=collector__pb2.AppCacheGetResponse.SerializeToString,
            ),
            'AppCacheSet': grpc.unary_unary_rpc_method_handler(
                    servicer.AppCacheSet,
                    request_deserializer=collector__pb2.AppCacheSetRequest.FromString,
                    response_serializer=collector__pb2.AppCacheSetResponse.SerializeToString,
            ),
            'AppCacheDelete': grpc.unary_unary_rpc_method_handler(
                    servicer.AppCacheDelete,
                    request_deserializer=collector__pb2.AppCacheDeleteRequest.FromString,
                    response_serializer=collector__pb2.AppCacheDeleteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'collector.CollectorPeer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('collector.CollectorPeer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CollectorPeer(object):
    """CollectorPeer — gRPC service between poll-workers/forwarder and their local cache-node.
    """

    @staticmethod
    def GetMyJobs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/collector.CollectorPeer/GetMyJobs',
            collector__pb2.GetJobsRequest.SerializeToString,
            collector__pb2.GetJobsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportExecution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/collector.CollectorPeer/ReportExecution',
            collector__pb2.ReportExecutionReq.SerializeToString,
            collector__pb2.ReportExecutionResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/collector.CollectorPeer/RegisterWorker',
            collector__pb2.RegisterWorkerReq.SerializeToString,
            collector__pb2.RegisterWorkerResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCredential(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/collector.CollectorPeer/GetCredential',
            collector__pb2.CredentialRequest.SerializeToString,
            collector__pb2.CredentialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/collector.CollectorPeer/SubmitResult',
            collector__pb2.SubmitResultRequest.SerializeToString,
            collector__pb2.SubmitResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAppCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/collector.CollectorPeer/GetAppCode',
            collector__pb2.AppCodeRequest.SerializeToString,
            collector__pb2.AppCodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AppCacheGet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/collector.CollectorPeer/AppCacheGet',
            collector__pb2.AppCacheGetRequest.SerializeToString,
            collector__pb2.AppCacheGetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AppCacheSet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/collector.CollectorPeer/AppCacheSet',
            collector__pb2.AppCacheSetRequest.SerializeToString,
            collector__pb2.AppCacheSetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AppCacheDelete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/collector.CollectorPeer/AppCacheDelete',
            collector__pb2.AppCacheDeleteRequest.SerializeToString,
            collector__pb2.AppCacheDeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
