"""Read / write / validate the customer's `secrets.env` file.

Contract enforced before every `monctl_ctl deploy`:
  * file exists
  * mode is 0600 (owner read/write only)
  * owned by the current uid
  * no placeholder values (empty or CHANGEME / TODO)

The installer refuses to proceed if any of these fail. A leaked or
accidentally-committed `secrets.env` effectively owns the cluster, so the
contract is deliberately strict.
"""
from __future__ import annotations

import os
import stat
from pathlib import Path

from monctl_installer.secrets.generator import SecretBundle, bundle_fieldnames

PLACEHOLDER_VALUES = {"", "CHANGEME", "TODO", "REPLACE_ME"}


class SecretsFileError(Exception):
    """Raised when secrets.env is missing, malformed, or insecurely permissioned."""


def write_secrets(bundle: SecretBundle, path: Path, *, overwrite: bool = False) -> None:
    if path.exists() and not overwrite:
        raise SecretsFileError(f"{path} already exists (pass overwrite=True to replace)")
    path.parent.mkdir(parents=True, exist_ok=True)
    # Create with 0600 atomically via O_CREAT|O_EXCL when possible.
    header = (
        "# MonCTL cluster secrets — generated by `monctl_ctl init`.\n"
        "# DO NOT COMMIT. DO NOT SHARE. DO NOT ROTATE MONCTL_ENCRYPTION_KEY "
        "without a planned migration.\n"
    )
    flags = os.O_WRONLY | os.O_CREAT | os.O_TRUNC
    fd = os.open(path, flags, 0o600)
    try:
        with os.fdopen(fd, "w") as fh:
            fh.write(header)
            for line in bundle.to_env_lines():
                fh.write(line + "\n")
    finally:
        # fdopen closes fd on context exit; guard is for the exotic failure path.
        pass
    # Re-chmod in case umask was restrictive enough to drop further.
    os.chmod(path, 0o600)


def validate_secrets_file(path: Path) -> None:
    if not path.exists():
        raise SecretsFileError(f"{path} does not exist — run `monctl_ctl init` first")
    st = path.stat()
    mode = stat.S_IMODE(st.st_mode)
    if mode != 0o600:
        raise SecretsFileError(
            f"{path} has mode {oct(mode)}; must be 0600 — run `chmod 600 {path}`"
        )
    if st.st_uid != os.getuid():
        raise SecretsFileError(
            f"{path} is owned by uid {st.st_uid}, current user is {os.getuid()} — "
            "refusing to deploy with mismatched ownership"
        )
    data = load_secrets(path)
    for key in bundle_fieldnames():
        env_key = _field_to_env_key(key)
        value = data.get(env_key)
        if value is None:
            raise SecretsFileError(f"{path}: missing required key {env_key}")
        if value in PLACEHOLDER_VALUES:
            raise SecretsFileError(
                f"{path}: {env_key} looks like a placeholder ({value!r}); "
                "re-run `monctl_ctl init` to generate real secrets"
            )


def load_secrets(path: Path) -> dict[str, str]:
    """Parse a KEY=VALUE env file into a dict. Ignores blank lines and comments.

    No shell-style expansion. Values are passed through verbatim to compose `.env`
    files on target hosts.
    """
    result: dict[str, str] = {}
    for raw in path.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            raise SecretsFileError(f"{path}: malformed line (no '='): {raw!r}")
        key, _, value = line.partition("=")
        result[key.strip()] = value.strip()
    return result


def _field_to_env_key(field_name: str) -> str:
    """`pg_password` → `PG_PASSWORD`, `monctl_jwt_secret_key` → `MONCTL_JWT_SECRET_KEY`."""
    return field_name.upper()
