# MonCTL Redis Sentinel configuration

port 26379
sentinel monitor monctl-redis 10.145.210.41 6379 2
sentinel down-after-milliseconds monctl-redis 5000
sentinel failover-timeout monctl-redis 30000
sentinel parallel-syncs monctl-redis 1
